Category.create!([
  { name: 'community', url: 'community' },
  { name: 'services', url: 'services' },
  { name: 'discussion forums', url: 'discussion forums' },
  { name: 'housing', url: 'housing' },
  { name: 'for sale', url: 'for sale' },
  { name: 'jobs', url: 'jobs' },
  { name: 'gigs', url: 'gigs' },
  { name: 'resumes', url: 'resumes' }
])


Category.create!([
  { name: 'activities', url: 'activities' },
  { name: 'artists', url: 'artists' },
  { name: 'childcare', url: 'childcare' },
  { name: 'classes', url: 'classes' },
  { name: 'events', url: 'events' },
  { name: 'general', url: 'general' },
  { name: 'groups', url: 'groups' },
  { name: 'local news' , url: 'local news' },
  { name: 'lost+found', url: 'lost+found' },
  { name: 'missed connections', url: 'mis },sed connections' },
  { name: 'musicians', url: 'musicians' },
  { name: 'pets', url: 'pets' },
  { name: 'politics', url: 'politics' },
  { name: 'rants & raves', url: 'rants &  },raves' },
  { name: 'rideshare', url: 'rideshare' },
  { name: 'volunteers', url: 'volunteers' }
])


Category.create!([
  { name: 'automotive', url: 'automotive' },
  { name: 'beauty', url: 'beauty' },
  { name: 'cell/mobile', url: 'cell/mobile', },
  { name: 'computer', url: 'computer' },
  { name: 'creative', url: 'creative' },
  { name: 'cycle', url: 'cycle' },
  { name: 'event', url: 'event' },
  { name: 'farm+garden', url: 'farm+garden', },
  { name: 'financial', url: 'financial' },
  { name: 'household', url: 'household' },
  { name: 'labor/move', url: 'labor/move' },
  { name: 'legal', url: 'legal' },
  { name: 'lessons', url: 'lessons' },
  { name: 'marine', url: 'marine' },
  { name: 'pet', url: 'pet' },
  { name: 'real estate', url: 'real estate' },
  { name: 'skilled trade', url: 'skilled trade' },
  { name: 'sm biz ads', url: 'sm biz ads' },
  { name: 'travel/vac', url: 'travel/vac' },
  { name: 'write/ed/tran', url: 'write/ed/tran' }
])
Category.create!([
  { name: 'android', url: 'android' },
  { name: 'apple', url: 'apple' },
  { name: 'arts', url: 'arts' },
  { name: 'atheist', url: 'atheist' },
  { name: 'autos', url: 'autos' },
  { name: 'beauty', url: 'beauty' },
  { name: 'bikes', url: 'bikes' },
  { name: 'celebs', url: 'celebs' },
  { name: 'comp', url: 'comp' },
  { name: 'cosmos', url: 'cosmos' },
  { name: 'diet', url: 'diet' },
  { name: 'divorce', url: 'divorce' },
  { name: 'dying', url: 'dying' },
  { name: 'eco', url: 'eco' },
  { name: 'feedbk', url: 'feedbk' },
  { name: 'film', url: 'film' },
  { name: 'fixit', url: 'fixit' },
  { name: 'food', url: 'food' },
  { name: 'frugal', url: 'frugal' },
  { name: 'gaming', url: 'gaming' },
  { name: 'garden', url: 'garden' },
  { name: 'haiku', url: 'haiku' },
  { name: 'help', url: 'help' },
  { name: 'history', url: 'history' },
  { name: 'housing', url: 'housing' },
  { name: 'jobs', url: 'jobs' },
  { name: 'jokes', url: 'jokes' },
  { name: 'legal', url: 'legal' },
  { name: 'linux', url: 'linux' },
  { name: 'manners', url: 'manners' },
  { name: 'marriage', url: 'marriage' },
  { name: 'money', url: 'money' },
  { name: 'music', url: 'music' },
  { name: 'open', url: 'open' },
  { name: 'outdoor', url: 'outdoor' },
  { name: 'parent', url: 'parent' },
  { name: 'pets', url: 'pets' },
  { name: 'philos', url: 'philos' },
  { name: 'photo', url: 'photo' },
  { name: 'politics', url: 'politics' },
  { name: 'psych', url: 'psych' },
  { name: 'recover', url: 'recover' },
  { name: 'religion', url: 'religion' },
  { name: 'rofo', url: 'rofo' },
  { name: 'science', url: 'science' },
  { name: 'spirit', url: 'spirit' },
  { name: 'sports', url: 'sports' },
  { name: 'super', url: 'super' },
  { name: 'tax', url: 'tax' },
  { name: 'travel', url: 'travel' },
  { name: 'tv', url: 'tv' },
  { name: 'vegan', url: 'vegan' },
  { name: 'words', url: 'words' },
  { name: 'writing', url: 'writing' }
])
Category.create!([
  { name: 'apts / housing', url: 'apts / housing' },
  { name: 'housing swap', url: 'housing swap' },
  { name: 'housing wanted', url: 'housing wanted' },
  { name: 'office / commercial', url: 'office / commercial' },
  { name: 'parking / storage', url: 'parking / storage' },
  { name: 'real estate for sale', url: 'real estate for sale' },
  { name: 'rooms / shared', url: 'rooms / shared' },
  { name: 'rooms wanted', url: 'rooms wanted' },
  { name: 'sublets / temporary', url: 'sublets / temporary' },
  { name: 'vacation rentals', url: 'vacation rentals' }
])
Category.create!([
  { name: 'antiques', url: 'antiques' },
  { name: 'appliances', url: 'appliances' },
  { name: 'arts+crafts', url: 'arts+crafts' },
  { name: 'atv/utv/sno', url: 'atv/utv/sno' },
  { name: 'auto parts', url: 'auto parts' },
  { name: 'aviation', url: 'aviation' },
  { name: 'baby+kid', url: 'baby+kid' },
  { name: 'barter', url: 'barter' },
  { name: 'beauty+hlth', url: 'beauty+hlth' },
  { name: 'bike parts', url: 'bike parts' },
  { name: 'bikes', url: 'bikes' },
  { name: 'boat parts', url: 'boat parts' },
  { name: 'boats', url: 'boats' },
  { name: 'books', url: 'books' },
  { name: 'business', url: 'business' },
  { name: 'cars+trucks', url: 'cars+trucks' },
  { name: 'cds/dvd/vhs', url: 'cds/dvd/vhs' },
  { name: 'cell phones', url: 'cell phones' },
  { name: 'clothes+acc', url: 'clothes+acc' },
  { name: 'collectibles', url: 'collectibles' },
  { name: 'computer parts', url: 'computer parts' },
  { name: 'computers', url: 'computers' },
  { name: 'electronics', url: 'electronics' },
  { name: 'farm+garden', url: 'farm+garden' },
  { name: 'free', url: 'free' },
  { name: 'furniture', url: 'furniture' },
  { name: 'garage sale', url: 'garage sale' },
  { name: 'general', url: 'general' },
  { name: 'heavy equip', url: 'heavy equip' },
  { name: 'household', url: 'household' },
  { name: 'jewelry', url: 'jewelry' },
  { name: 'materials', url: 'materials' },
  { name: 'motorcycle parts', url: 'motorcycle parts' },
  { name: 'motorcycles', url: 'motorcycles' },
  { name: 'music instr', url: 'music instr' },
  { name: 'photo+video', url: 'photo+video' },
  { name: 'rvs+camp', url: 'rvs+camp' },
  { name: 'sporting', url: 'sporting' },
  { name: 'tickets', url: 'tickets' },
  { name: 'tools', url: 'tools' },
  { name: 'toys+games', url: 'toys+games' },
  { name: 'trailers', url: 'trailers' },
  { name: 'video gaming', url: 'video gaming' },
  { name: 'wanted', url: 'wanted' },
  { name: 'wheels+tires', url: 'wheels+tires' }
])

Category.create!([
  { name: 'accounting+finance', url: 'accounting+finance' },
  { name: 'admin / office', url: 'admin / office' },
  { name: 'arch / engineering', url: 'arch / engineering' },
  { name: 'art / media / design', url: 'art / media / design' },
  { name: 'biotech / science', url: 'biotech / science' },
  { name: 'business / mgmt', url: 'business / mgmt' },
  { name: 'customer service', url: 'customer service' },
  { name: 'education', url: 'education' },
  { name: 'etc / misc', url: 'etc / misc' },
  { name: 'food / bev / hosp', url: 'food / bev / hosp' },
  { name: 'general labor', url: 'general labor' },
  { name: 'government', url: 'government' },
  { name: 'human resources', url: 'human resources' },
  { name: 'legal / paralegal', url: 'legal / paralegal' },
  { name: 'manufacturing', url: 'manufacturing' },
  { name: 'marketing / pr / ad', url: 'marketing / pr / ad' },
  { name: 'medical / health', url: 'medical / health' },
  { name: 'nonprofit sector', url: 'nonprofit sector' },
  { name: 'real estate', url: 'real estate' },
  { name: 'retail / wholesale', url: 'retail / wholesale' },
  { name: 'sales / biz dev', url: 'sales / biz dev' },
  { name: 'salon / spa / fitness', url: 'salon / spa / fitness' },
  { name: 'security', url: 'security' },
  { name: 'skilled trade / craft', url: 'skilled trade / craft' },
  { name: 'software / qa / dba', url: 'software / qa / dba' },
  { name: 'systems / network', url: 'systems / network' },
  { name: 'technical support', url: 'technical support' },
  { name: 'transport', url: 'transport' },
  { name: 'tv / film / video', url: 'tv / film / video' },
  { name: 'web / info design', url: 'web / info design' },
  { name: 'writing / editing', url: 'writing / editing' }
])

Category.create!([
  { name: 'computer', url: 'computer' },
  { name: 'creative', url: 'creative' },
  { name: 'crew', url: 'crew' },
  { name: 'domestic', url: 'domestic' },
  { name: 'event', url: 'event' },
  { name: 'labor', url: 'labor' },
  { name: 'talent', url: 'talent' },
  { name: 'writing', url: 'writing' }
])